name: Automated Tests

# Evento a ser escutado
on: pull_request

# O que ser√° executado quando evento ocorrer
jobs:
  jest:
    name: Jest Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/jod"

      - run: npm ci #instalar dependencias

      - run: npm test #rodar testes


